export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAILED = "AUTH_FAILED";

export const CHECK_NODE_STATUS_START = "CHECK_NODE_STATUS_START";
export const CHECK_NODE_STATUS_SUCCESS = "CHECK_NODE_STATUS_SUCCESS";
export const CHECK_NODE_STATUS_FAILURE = "CHECK_NODE_STATUS_FAILURE";

export const GET_BLOCK_LIST_START = "GET_BLOCK_LIST/start";
export const GET_BLOCK_LIST_SUCCESS = "GET_BLOCK_LIST/success";
export const GET_BLOCK_LIST_FAILURE = "GET_BLOCK_LIST/failure";

export const SESSION_SET_SELECTED_ACCOUNT = "SESSION_SET_SELECTED_ACCOUNT";
export const SESSION_SIGN_OUT = "SESSION_SIGN_OUT";
